# Generated by Django 5.2.9 on 2026-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='http_method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='request_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='status_code',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
